# Generated by Django 3.1.2 on 2020-10-21 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201008_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_sold',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
